### PR TITLE
Persist custom config settings across restarts

### PR DESCRIPTION
**Pull request by kocolosk**
## Overview

This bug appears similar to #78 but the underlying code is quite different and so I went ahead and submitted a separate issue.

The end result is the same -- any settings configured via the `_config` endpoint are lost when the container restarts using the `dev` image. This is because in `dev` the `local.d/docker.ini` file is now the last file in the chain, and the `docker-entrypoint.sh` overwrites it on startup.

As @Maxima078 pointed out, the problem does not exist on 2.1.1, because we have a `local.d/local.ini` file which is last in the chain. In #50 we moved this file to `default.d` and inadvertently introduced this bug.

Some constraints on a possible solution:
* From Kubernetes' perspective it would be good to *always* have a file in `local.d` as the last file in the chain, as we can configure `local.d` to be backed by persistent storage. Currently if we run the `dev` image in admin party mode custom configuration is written to `etc/local.ini` which would also not survive a Pod being rescheduled onto a different node.
* We should not expose the admin password in plaintext for any significant length of time. Currently in the `2.1.1` image we do leave the unencrypted password sitting in `local.d/docker.ini` as we're writing the encrypted version to `local.d/local.ini`.

The best idea I have at the moment is 
1. `touch` the `docker.ini` file every time
2. append the `[admins]` entry to the file only if a hashed version of the username is not already present (this has the added benefit of not overriding any password changes submitted via `_config`)
3. do the same conditional append for `[couch_httpd_auth]`

And so that's what I've attempted to do here.

## Testing recommendations

Build an image using this branch and start up a container. Make some config changes using `_config`, restart the container and see if it sticks. Also try changing the admin user password and see that it survives a restart.

## Related Pull Requests

#50 (changed behavior since 2.1.1)
#78 (similar issue in 1.x)

## Checklist

- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by kocolosk** [comment]
CI failed because of some seemingly unrelated issue with webpack on the dev builds: https://travis-ci.org/apache/couchdb-docker/jobs/381673067#L4861-L4884

**Comment by wohali** [comment]
We will need this fix on 2.1.x as well...

**Comment by wohali** [comment]
@kocolosk how do we handle backing `vm.args` by persistent storage? or is that not a concern?

**Comment by kocolosk** [comment]
@wohali thanks for backporting. I don't think `vm.args` is quite the same issue because we don't offer any way to modify it during runtime.

We should probably improve the Helm chart to allow users to customize `vm.args` when they provision a cluster like we do with `default.d/docker.ini`. The challenge there will be that `vm.args` location doesn't lend itself to a natural `ConfigMap` mount point. Will have to think on that a bit.

**Comment by wohali** [comment]
@kocolosk options might include using the `-args_file` option to move the `vm.args` file, or perhaps changing where CouchDB itself keeps it if you want. I wouldn't want our current, arbitrary `etc/` directory layout to hold up k8s adoption.

**Pull request merged**
