### PR TITLE
Improve README for configuration changes, closes #47

### PR DESCRIPTION
**Pull request by wohali**
## Overview

README.md was misleading on the desired approach for making configuration changes, leading to PRs like #32. This makes it clearer that if you need more than you can get from a few simple env vars, you should be mounting `/opt/couchdb/etc/local.d` as a volume and persisting it to disk.

By specifying the `local.d` subdirectory we ensure that upstream image default changes to `/opt/couchdb/etc/default.ini`, as well as docker-specific upstream changes in `/opt/couchdb/etc/default.d`, are unaffected by externalisation of this volume.

## Testing recommendations

Read it!

## GitHub issue number

Closes #47

## Checklist

- [X] Documentation reflects the changes;

### CODE REVIEW

**Comment by wohali** [comment]
One weakness of this approach is that it means you cannot externalise `/opt/couchdb/etc/vm.args`.

I am torn on this point. There are parameters in there (like the erlang cookie) that would be good to persist.

However, externalising the entire `/opt/couchdb/etc` directory prevents us from slipstreaming changes to `default.ini` and `default.d/*` into the image successfully.

Perhaps we just add a new env var just for `ERLANG_COOKIE` and wipe our hands of it.

**Comment by chriswiggins** [comment]
The issue with not being able to expose `vm.args` is that there are other things that cannot be changed. We run a RabbitMQ Cluster on the same hosts as our CouchDB cluster, which means that we need to change the `epmd` port. We also changed the node name too.

I think with docker that it's possible to bind-mount files as well as directories isn't it?

**Comment by wohali** [comment]
@chriswiggins sadly, no: ["Further, the source of a bind mount must be a local directory, not a file."](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v-read-only)

**Comment by wohali** [comment]
Looks like as long as you're not on Windows, you can bind-mount a single file. I'll update.

Any other comments?

**Pull request merged**
