### PR TITLE
Make secret configurable via environment

### PR DESCRIPTION
**Pull request by domachine**
## Overview

This applies the changes mentioned in #9. Hopefully this makes the Dockerfile ready to be released on docker-hub.

## Testing recommendations

This can be tested by running a container based on the image and inspecting it with `docker exec` to verify that the `etc/local.d/secret.ini` file is successfully injected.

## GitHub issue number

https://github.com/apache/couchdb-docker/issues/9

## Checklist

- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by wohali** [comment]
A problem with this PR is that because the file you're creating alphabetically sorts later than `docker.ini`, the admin user will be written into it instead of `docker.ini`.

Can you rename the file something like `10-secret.ini` so `docker.ini` will be properly overwritten with the crypttext of the password correctly, please?

Note to self: Further to this we need to fix `vm.args` so that the `inet_dist_listen` port range is larger than a single port, otherwise the maximum cluster size will be 2. We will also need to expand the list of exposed ports in the `Dockerfile`.

**Comment by domachine** [comment]
@wohali Sure 👍

**Comment by domachine** [comment]
Maybe I could also just append the line to the `docker.ini` file, what do you think?

**Comment by wohali** [comment]
Either or, your choice.

**Comment by domachine** [comment]
Ok, I went for appending to `docker.ini`. Feels cleaner :-). Thanks for taking your time.

**Pull request merged**
