### PR TITLE
fix: set $HOME when stepping down from root

### PR DESCRIPTION
**Pull request by willholley**
## Overview

Why:

In https://github.com/apache/couchdb-docker/pull/234 we moved from using `gosu` to `setpriv` to step down from the root user to the couchdb user.

There is a behavioural difference between and `gosu` and `setpriv` in that `gosu` will [set the $HOME environment variable](https://github.com/tianon/gosu/blob/master/setup-user.go#L45) to that of the target user.

Without this behaviour, `couchdb` includes the root user home directory (`/root`) in various search paths and crashes because it doesn't have read permissions.

How:

Explicitly set `$HOME` to the `couchdb` user home directory before we execute as the `couchdb` user, replicating the `gosu` behaviour.

## Testing recommendations

The easiest reproducer is:

```
$ docker run -it -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -eNODENAME=foo couchdb:3.2.2

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{{error,\"Error when reading /root/.erlang.cookie: eacces\"},[{auth,init_cookie,0,[{file,\"auth.erl\"},{line,290}]},{auth,init,1,[{file,\"auth.erl\"},{line,144}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{{error,"Error when reading /root/.erl

Crash dump is being written to: erl_crash.dump...done
```

## GitHub issue number

https://github.com/apache/couchdb-docker/issues/236

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by rnewson** [comment]
suggest adding `--reset-env` to the `setpriv` line instead.

**Review by rnewson — APPROVED** [review]

**Comment by aolmosj** [comment]
Hi!

What's the ETA for this being pushed to Dockerhub? It looks like the current version it's still having this issue. I'm having this error when setting the variable `COUCHDB_ERLANG_COOKIE`.

```Error when reading /root/.erlang.cookie```

Thanks!

**Comment by willholley** [comment]
@aolmosj the fix is published for the `apache/couchdb:3.3.1` image. We'll push the update to `apache/couchdb:3.2.2` as well shortly.

**Comment by willholley** [comment]
@aolmosj note the `apache/couchdb` image is different to the `couchdb` image published by docker. The latter may take a while to be updated - we don't control that directly.

**Pull request merged**
