### PR TITLE
Fix for initial startup time (#131)

### PR DESCRIPTION
**Pull request by spoyd**
## Overview
Initial startup time (first execution) on some docker hosts is >50 seconds. This is caused by updating the ownership of more than 1600 files during the first execution of an instance of this container. These files are all static in the container and could be modified at container build time instead of at runtime.

## Testing recommendations
Startup time for the container should be < 3 seconds.

## GitHub issue number
#131 

## Related Pull Requests
n/a

## Checklist
- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by wohali** [comment]
@kocolosk please review?

**Comment by kocolosk** [comment]
I could have sworn we already made this change ...

**Comment by kocolosk** [comment]
Ah, no - the changes in #110 were scoped to the `docker-entrypoint.sh` file. I will review.

**Comment by wohali** [comment]
@kocolosk poke. this missed the 2.3.1 image but could land in 2.4.0.

**Comment by spoyd** [comment]
@wohali What do I need to do to complete the checklist and get this accepted?

**Comment by kocolosk** [comment]
@spoyd I will get back to you in < 24h if anything is needed, sorry for the delay

**Comment by kocolosk** [comment]
@spoyd looks good and correct - sorry this took so long to review. Can you make the same change in the `dev/Dockerfile` and most importantly the `2.3.1/Dockerfile` (which didn't exist when you filed this PR) so we make sure it gets carried forward to new official image builds? Then I'm happy to merge.

**Comment by wohali** [comment]
@spoyd ping, are you able to clean up this PR please? Thanks. See @kocolosk 's comment above.

**Comment by wohali** [comment]
Closing in favour of #144

**Pull request closed without merging**
