### PR TITLE
Speed up startup time, fixes #131

### LINKED ISSUE #131: Initial startup time is too long
Docker container initial startup time too long.

## Expected Behavior
Startup time should be minimal, preferably under 1 second.

## Current Behavior
Docker container initial startup time is close to 60 seconds.

## Possible Solution
Shorten the time it takes to execute the ```chown``` steps in the ```docker-entrypoint.sh``` script.

## Steps to Reproduce (for bugs)
1. Launch a contain using the existing image using:  
    ```docker run couchdb:latest```
1. Record the time it takes to print the first lines of output.

## Context
I discovered this issue while trying to automate the testing of my CouchDB backups. I was using a script to create a CouchDB container, restore the database backup, execute some queries, and destroy the container. The script was timing out because of the extremely long startup time of the CouchDB container.

## Your Environment
* Version used:  
   CouchDB Image: couchdb:2.3.0  

* Docker Info
```
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 43
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d007b64
ID: 74Q5:SZUE:ROUC:HXQI:6MLC:D45V:ENBH:E7TL:6SWA:FROI:CLBM:NRYL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 62
 Goroutines: 77
 System Time: 2019-02-06T02:09:46.8639059Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```   

* Browser Name and version:  
  Version 71.0.3578.98 (Official Build) (64-bit)

* Operating System and version (desktop or mobile):
   Windows 10 / 1809

* Link to your project:  
   n/a

### PR DESCRIPTION
**Pull request by wohali**
See #132 - this is the revised version.

Already +1 by @kocolosk .

### CODE REVIEW

**Comment by kocolosk** [comment]
Nice, thanks for cleaning this up @wohali

**Comment by arturog** [comment]
@wohali: Hello, I am a bit confused by this commit/PR.  Are we setting *all* files under /opt/couchdb as owned by the running process (couchdb)?  I feel we should get binaries, etc, to be owned by root.

Can you point me in the right direction to understand why this was necessary?  Thanks!

**Comment by wohali** [comment]
If the data and config files aren't owned by `couchdb` then the database won't function correctly.

**Comment by arturog** [comment]
Understood, but the commands in the Dockerfile and docker-entrypoint.sh are setting *all* files under /opt/couchdb to be owned by the couchdb user -that can't be right.

I think we should only set ownership on /opt/couchdb/data, logs, etc...  Otherwise the running process has permissions to write over the binaries.  Shall we fix this?

**Pull request merged**
